### ISSUE TITLE
questions about the dataset

### ISSUE THREAD

**Issue by hm1229** [Alibaba-NLP/OmniSearch#1]
why there are some english questions only have chinese answers in the DynVQA_en? and the metric uses recall?

**Comment by YangningLi1** [comment]
The issue is due to an error in our processing, not the data itself. We will fix this as soon as possible.

**Comment by hm1229** [comment]
thanks a lot

**Comment by liangbingzhao** [comment]
@YangningLi1 Why the newest data still part of it do not have the english answers. so the 202412 is the most stable one?

**Comment by xandery-geek** [comment]
The problem remains unsolved.
